### ISSUE TITLE
new issue - with complexfunction/function  constructors

### ISSUE THREAD

**Issue by AviChickvashvili** [VadimKachevski/OOP_Ex1#5]
Hello again , 
were facing a new bug inside Junit complexfunction contructors test 
im sending the bug right now
	function p = null;
		ComplexFunction cf2 = new ComplexFunction(p);
		System.out.println(cf2);
the program throws with 
java.lang.NullPointerException

**Comment by VadimKachevski** [comment]
Hi again, and thanks for your cooperation !
the bug should be fixed now.
:)

**Comment by AviChickvashvili** [comment]
Hello 
The bug was not fixed yet while i was testing the complex function contructor again

while sending null as operation , we got error : java.lang.NullPointerException 

im attaching the code 👍  
String oper = null;
		Monom mx = new Monom("1");
		function pe = null;
		
		ComplexFunction cf20 = new ComplexFunction(oper,mx,mx);

thanks in regards.

**Comment by VadimKachevski** [comment]
what??!? i fixed it, you didn't pull right, try again.
